-keep class com.google.mediapipe.** { *; }
-dontwarn com.google.mediapipe.**
# MediaPipe / AutoValue annotation-processor stubs referenced from AARs (not needed at runtime).
-dontwarn javax.annotation.processing.AbstractProcessor
-dontwarn javax.annotation.processing.SupportedAnnotationTypes
-dontwarn javax.lang.model.SourceVersion
-dontwarn javax.lang.model.element.Element
-dontwarn javax.lang.model.element.ElementKind
-dontwarn javax.lang.model.element.Modifier
-dontwarn javax.lang.model.type.TypeMirror
-dontwarn javax.lang.model.type.TypeVisitor
-dontwarn javax.lang.model.util.SimpleTypeVisitor8
-dontwarn com.google.auto.value.**
-dontwarn autovalue.shaded.**
